---
title: "Getting started with Shiny"
output: html_document
date: "2022-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Loading the data and necessary packages

```{r}
library(shiny)
library(vroom)
library(tidyverse)
```

```{r}
#Getting the data

dir.create("neiss")

download <- function(name) {
  url <- "https://github.com/hadley/mastering-shiny/raw/master/neiss/"
  download.file(paste0(url, name), paste0("neiss/", name), quiet = TRUE)
}
download("injuries.tsv.gz")
download("population.tsv")
download("products.tsv")
```

```{r}
#Reading the injuries data

injuries <- vroom("neiss/injuries.tsv.gz")

injuries
```

```{r}
#Reading the injuries data

products <- vroom("neiss/products.tsv")
products


population <- vroom("neiss/population.tsv")
population

```
# Data Exploration

```{r}
selected <- injuries %>% 
    filter(prod_code == 649)

nrow(selected)
  
```

```{r}
selected %>%
    count(location, wt = weight, sort = TRUE)
```

```{r}
selected %>% 
    count(body_part, wt = weight, sort = TRUE)
```
```{r}
 selected %>% 
    count(diag, wt = weight, sort = TRUE)
```
```{r}
summary <- selected %>% 
  count(age, sex, wt = weight)

summary
    
summary %>% 
    ggplot(aes(x = age, y = n, colour = sex)) + 
    geom_line() + 
    labs(y = "Estimated number of injuries")


```
```{r}
summary <- selected %>% 
  count(age, sex, wt = weight) %>% 
  left_join(population, by = c("age", "sex")) %>% 
  mutate(rate = n / population * 1e4)

summary
```
```{r}
summary %>% 
  ggplot(aes(x = age, y = rate, colour = sex)) + 
  geom_line(na.rm = TRUE) + 
  labs(y = "Injuries per 10,000 people")
```

```{r}
selected %>% 
  sample_n(10) %>% 
  pull(narrative)
```





